# Cloudflare Workers配置文件
name = "hbmusic-api"
main = "worker.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# 开发环境配置
[dev]
port = 8787
local_protocol = "https"

# 环境变量配置
[vars]
API_BASE_URL = "https://api.931125.xyz"

# 路由配置
[[routes]]
pattern = "apiback.931125.xyz"  # 根路径
zone_name = "931125.xyz"

[[routes]]
pattern = "apiback.931125.xyz/*"  # 所有路径
zone_name = "931125.xyz"

# 触发器配置
[triggers]
crons = []

# 其他设置
[site]
bucket = "./public" # 如果有静态资源

# 自定义域名
[env.production]
routes = [
  { pattern = "apiback.931125.xyz", zone_name = "931125.xyz" },
  { pattern = "apiback.931125.xyz/*", zone_name = "931125.xyz" }
] 